name: Lint Check

on: 
    pull_request:
    push: 
        branches:
            - main 
            
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: ./server
        run: npm install

      - name: Run ESLint
        working-directory: ./server
        run: npm run lint
