name: Run Test

on: 
    pull_request:
        branches:
            - '**'
    push: 
        branches:
            - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: ./server
        run: npm ci

      - name: Generate Prisma Client
        working-directory: ./server
        run: npx prisma generate

      - name: Run Tests
        working-directory: ./server
        run: NODE_OPTIONS=--experimental-vm-modules npm test
